config/routes.rb
Gr8picRails::Application.routes.draw do

  get "log_in" => "sessions#new"
  get "log_out" => "sessions#destroy"
  get "sign_up" => "users#new"
  get "photos_show" => "photos#show"

  resources :users
  resources :sessions
  resources :ratings
  resources :photos

  get "welcome/index"
  get "welcome/about"

  root :to => 'welcome#index'

end

app/models/history.rb
class History < ActiveRecord::Base
  attr_accessible :snapshot
  has_many :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  has_many :ratings
  has_attached_file :image, 
    :styles => { 
    :thumb => "100x100#",
    :small => "150x150>",
    :medium => "400x400>",
    :large => "700x700>"}

  def update_photo_ratings
    #This query may need work later. At large scale, the last photo id may
    #not be the same one user rated. Change to find Rating.value based on user_id on rating.
    self.ratings_total += Rating.where(:photo_id => self).last.value
    self.ratings_count += 1
    self.ratings_ave = self.ratings_total / self.ratings_count
    self.save!
  end  
  
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :value, :photo_id, :user_id
  belongs_to :photo
  belongs_to :user

  private
  after_save :recalculate_photo

  def recalculate_photo
    photo.update_photo_ratings if photo
  end

  def self.unrated(current_user_id)
    return_val = nil
    every_photo = []
    user_ratings = Rating.where(:user_id => current_user_id).each
    for photo in user_ratings
      every_photo << photo.photo_id
    end

    for id in (1..Photo.count)
      if every_photo.include?(id) == false
        return_val = Photo.find(id)
      end
    end
    return_val
  end

  def self.winner  #PROBLEM --> what about ties?
    best_photo = Photo.maximum("ratings_ave")
    Photo.where(:ratings_ave => best_photo).first
  end
	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :photos
  has_many :ratings, :through => :photos
	attr_accessible :name, :email, :password, :password_confirmation

	attr_accessor :password
	before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
  	user = find_by_email(email)
  	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
  		user
  	else
  		nil
  	end
  end

  def encrypt_password
  	if password.present?
  		self.password_salt = BCrypt::Engine.generate_salt
  		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  	end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all
  end

  def create
    unless params[:photo].nil?
      @photo = Photo.create(params[:photo].merge({:user_id => current_user.id}))

      if @photo.save
        redirect_to new_rating_path
      else
        redirect_to new_photo_path
      end
    else
      redirect_to new_photo_path, :notice => "You must choose a photo to upload"
    end
  end

  def new
    @photo = Photo.new
    @user = User.new
  end

  def update
    @photo = Photo.create(params[:photo].merge({:user_id => current_user.id}))

    if @photo.save
      redirect_to ratings_path
    else
      redirect_to new_photo_path
    end
  end

  def destroy
  end

  def show
    @photo = Photo.find(params[:id])
  end
  
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
    @winning_photo = Rating.winner
    @winning_user = User.find(@winning_photo.user_id).name
  end


  def create
    @rating = Rating.new(params[:rating].merge({:user_id => current_user.id}))
    
    if @rating.save
      redirect_to :back
    else
      render "new"
    end
  end

  def new
    unless current_user.nil?
      @photo = Rating.unrated(current_user.id)
    else
      @photo = Photo.all.sample
    end

    @rating = Rating.new
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:email], params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to new_photo_path, :notice => "Logged in!"
  	else
  		flash.now.alert = "Invalid email or password"
  		render "new"
  	end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
   
    if @user.save
      session[:user_id] = @user.id
      redirect_to new_photo_path 
    else
      flash[:error] = @user.errors.empty? ? "Error" : @user.errors.full_messages.to_sentence
      redirect_to new_user_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  	@winning_photo = Rating.winner
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gr8picRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
	<% if current_user %>
		<li>Logged in as <%= current_user.name %></li><br />
		<li><%= link_to "Log out", log_out_path %></li>
	<% else %>
		<div class="button"><%= link_to "Sign up", sign_up_path %></div> 
		<div class="button"><%= link_to "log in", log_in_path %></div>
	<% end %>
</div>
	
	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
	<% end %>

<%= yield %>

	<% if current_page?(root_url) %>
		<footer>
			<div class="button"> <a href="welcome/about">ABOUT</a><div>
		</footer>
	<% else %>
		<footer>
			<div class="button"> <%= link_to "Home", root_path %></div>
		</footer>
	<% end %>

</body>
</html>

app/views/photos/_signup_form.html.erb
<div class="main_container">
<li>
	<h1>Sign Up</h1>
	<span class="small_font">so we know which photo is yours!</span>
<%= form_for @user do |x| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= x.label :name %><br />
		<%= x.text_field(:name, :placeholder => "name") %>
	</p>
	<p>
		<%= x.label :email %><br />
		<%= x.text_field(:email, :placeholder => "email") %>
	</p>
	<p>
		<%= x.label :password %><br />
		<%= x.password_field(:password, :placeholder => "password") %>
	</p>
	<p>
		<%= x.label :password_confirmation %><br />
		<%= x.password_field :password_confirmation %>
	</p>

	<%= x.submit "Create Account" %>
<% end %>
	</li>
</div>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/index.html.erb
<h1>All Photos</h1>
<% if current_user.nil? %>
	<p>You must <%= link_to "sign up", sign_up_path %> or <%= link_to "login", log_in_path %> to see all photos!</p>
<% else %>
	<h1><div class="button"> <%= link_to "Home", root_path %></div></h1>
	<% for photo in @photos %>
		<li><div>
		<%= link_to(image_tag(photo.image.url(:medium)), photo) %>
		</div></li>
	<% end %>
<% end %>
<!-- This needs work. Trying to get individual photos to show large view from link from history (photos#index) -->

app/views/photos/new.html.erb
<% unless current_user.nil? %>
	<h1>Upload a Photo</h1>

	<%= form_for(@photo, :html => { :multipart => true }) do |f| %>
		<%= f.file_field :image %>
		<%= f.submit "Upload" %>
	<% end %>
	
	<br />
	
<% else %>
	<%= render "signup_form" %>
<% end %>

app/views/photos/show.html.erb
<% if current_user.nil? %>
	<%= render "signup_form" %>
	<br />
	
<% else %>
	<div class="button"><%= link_to "All Photos", photos_path %></div>
	<div class="main_container">
		<li><%= link_to image_tag(@photo.image.url), photos_path %></li>
	<br />
	</div>
<% end %>
<!-- This needs work. Trying to get individual photos to show large view from link from history (photos#index) -->

app/views/ratings/_done_rating.html.erb
<p>You've rated them all. Upload to rate more --></p>

app/views/ratings/index.html.erb
<div class="main_container">

<h1>Ratings</h1>
		<p>Yesterday's highest rated photo by total rating is:</p>
			<li>Photo ID: <%= @winning_photo.id %></li>
			<li>User ID: <%= @winning_photo.user_id %></li>
			<li>User Name: <%= @winning_user %></li><br>
			<li><%= image_tag @winning_photo.image.url, {:height => 500} %></li>
</div>

app/views/ratings/new.html.erb
<div class="main_container">
	<h1>Rate!</h1>
	<li>
		<div class="button"><%= link_to "All Photos", photos_path %></div>
	</li>
	<li>
		<div>
			<% unless @photo.nil? %>

				<% if current_user.nil? %>
					<p>You must <%= link_to "sign up", sign_up_path %> or <%= link_to "login", log_in_path %> to rate photos!</p>
				<% else %>
					<p>Random photo generated below. Rate it by number of stars...</p>
					<%= form_for @rating do |f| %>
					<div>
						<%= f.radio_button :value, 1 %>
						<%= f.label "1" %>
						<%= f.radio_button :value, 2 %>
						<%= f.label "2" %>
						<%= f.radio_button :value, 3, {:checked => true} %>
						<%= f.label "3" %>
						<%= f.radio_button :value, 4 %>
						<%= f.label "4" %>
						<%= f.radio_button :value, 5 %>
						<%= f.label "5" %>
					</div> 
						<%= f.hidden_field :photo_id, :value => @photo.id %>
						<%= f.submit "Rate!", :class => "button" %>
					<% end %><br />
				<% end %>
				<%= image_tag @photo.image.url %>
			<% else %>
				<%= render "done_rating" %>

			<% end %>
		</div>
	</li>
	<li>
		<div class="button"><%= link_to "UPLOAD", new_photo_path %></div>
	</li>
</div>

app/views/ratings/show.html.erb
<h1>Ratings#show</h1>
<p>Find me in app/views/ratings/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<% if current_user %>	
	<p>need a 404</p>
<% else %>
	<h1>Sign Up</h1>
	<span>New users, please sign up below...</span><br>
	<span class="small_font">so we know which photo is yours!</span>


	<%= form_for @user do |x| %>
		<% if @user.errors.any? %>
			<div class="error_messages">
				<h2>Form is invalid</h2>
				<ul>
					<% for message in @user.errors.full_messages %>
						<li><%= message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<p>
			<%= x.label :name %><br />
			<%= x.text_field(:name) %>
		</p>
		<p>
			<%= x.label :email %><br />
			<%= x.email_field(:email) %>
		</p>
		<p>
			<%= x.label :password %><br />
			<%= x.password_field(:password) %>
		</p>
		<p>
			<%= x.label :confirm_password %><br />
			<%= x.password_field :password_confirmation %>
		</p>

		<%= x.submit "Create Account" %>
	<% end %>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/about.html.erb
<html>

<body>
	<header>About</header><br>
	<!--This page will explain how the site works, and link to each explanation. For now, it's an 'infographic'-->
	
	<%= image_tag "mockup.png", {:height => 600} %>

	
	
</body>
</html>

app/views/welcome/index.html.erb
<html>
<body>

	<header><%= link_to "Gr8pic", root_path %></header><br />
	
	<h1>Upload your photo. Browse & rate the rest. (best below)</h1>

	<div class="main_container"> <!--main container for rate button
main picture, and upload button -->
			
		<li><div class="button"> <%= link_to "RATE", new_rating_path %> </div></li>
		<li><div>
			<% if @winning_photo.nil? %>
				<p>No photo yet</p>
			<% else %> 
				 <%= link_to image_tag(@winning_photo.image.url), new_rating_path %>
			<% end %>
			 <!--PLACEHOLDER image_tag("http://gr8pic.com/pictures/cat_picture.jpeg")-->
		</div></li>
		<li><div class="button"><%= link_to "UPLOAD", new_photo_path %></div></li>
		
	</div>

</body>
</html>